### PR TITLE
chore: update dev docs to use local registry

### PR DESCRIPTION
**Pull request by BobyMCbobs**
remove requirement for access to ghcr.io/cncf-infra/verify-conformance

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
@heyste @iiamabby, please verify these updated docs work. Testing for local-only registry.

**Comment by iiamabby** [comment]
All works as expected for me :)

**Comment by heyste** [comment]
When I applied the "build / `kubectl apply` step" is failed due to not finding the `token`

```
/tmp/verify-conformance/hack/local-dev$ kustomize build . | kubectl apply -f -
Error: loading KV pairs: file sources: [token=./tmp/token]: evalsymlink failure on '/tmp/verify-conformance/hack/local-dev/tmp/token' : lstat /tmp/verify-conformance/hack/local-dev/tmp: no such file or directory
error: no objects passed to apply
```
If I create the `hmac` and `token` so they are in the required path then things look to be all okay.

```
/tmp/verify-conformance/hack/local-dev$ mkdir -p ./tmp/
/tmp/verify-conformance/hack/local-dev$ echo "$(openssl rand -base64 15)" > ./tmp/hmac
/tmp/verify-conformance/hack/local-dev$ gh auth token > ./tmp/token

/tmp/verify-conformance/hack/local-dev$ kustomize build . | kubectl apply -f -
namespace/prow created
configmap/local-registry-hosting created
configmap/plugins created
configmap/vcr-config created
secret/github-token created
secret/hmac-token created
service/ghproxy created
persistentvolumeclaim/ghproxy created
deployment.apps/ghproxy created
deployment.apps/verify-conformance-release created
```

**Comment by BobyMCbobs** [comment]
> When I applied the "build / `kubectl apply` step" is failed due to not finding the `token`
> 
> ```
> /tmp/verify-conformance/hack/local-dev$ kustomize build . | kubectl apply -f -
> Error: loading KV pairs: file sources: [token=./tmp/token]: evalsymlink failure on '/tmp/verify-conformance/hack/local-dev/tmp/token' : lstat /tmp/verify-conformance/hack/local-dev/tmp: no such file or directory
> error: no objects passed to apply
> ```
> 
> If I create the `hmac` and `token` so they are in the required path then things look to be all okay.
> 
> ```
> /tmp/verify-conformance/hack/local-dev$ mkdir -p ./tmp/
> /tmp/verify-conformance/hack/local-dev$ echo "$(openssl rand -base64 15)" > ./tmp/hmac
> /tmp/verify-conformance/hack/local-dev$ gh auth token > ./tmp/token
> 
> /tmp/verify-conformance/hack/local-dev$ kustomize build . | kubectl apply -f -
> namespace/prow created
> configmap/local-registry-hosting created
> configmap/plugins created
> configmap/vcr-config created
> secret/github-token created
> secret/hmac-token created
> service/ghproxy created
> persistentvolumeclaim/ghproxy created
> deployment.apps/ghproxy created
> deployment.apps/verify-conformance-release created
> ```

@heyste, thank you for taking a look. I've adjusted the doc so it should just work

**Comment by BobyMCbobs** [comment]
I just verified these docs on a clean-install Bluefin machine

**Pull request merged**
